[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hpc4-tutorial"
authors = [{name = "kftse-ust-hk", email = "kftse@ust.hk"}]
dynamic = ["version", "description"]
